//
// Created by emman on 16/02/2023.
//

#ifndef GA_CNN_DEFINES_CUH
#define GA_CNN_DEFINES_CUH

#define H2D cudaMemcpyHostToDevice
#define D2H cudaMemcpyDeviceToHost

#define CHECK(call) {\
    const cudaError_t error = call;\
    if (error != cudaSuccess) {\
        printf("Error: %s:%d, ", __FILE__, __LINE__);\
        printf("code: %d, reason: %s\n", error, cudaGetErrorString(error));\
        exit(1);\
    }\
}

#define CONV_SIZE (26*26*NUM_FILTERS)
#define POOLED_SIZE (13*13*NUM_FILTERS)
#define TOURNAMENT_SIZE 10
#define IMAGE_INPUT_SIZE (28*28)
#define CONV_IMAGE_SIZE (26*26)
#define OUTPUT_PER_FILTER (10 * NUM_FILTERS)

#define FILTER_SIZE 3
#define NUM_FILTERS 5
#define POOLED_IMAGE_SIZE 13
#define NUM_WEIGHTS (NUM_FILTERS * FILTER_SIZE * FILTER_SIZE + POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS * 10)
#define NET0 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 0 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET1 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 1 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET2 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 2 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET3 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 3 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET4 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 4 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET5 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 5 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET6 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 6 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET7 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 7 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET8 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 8 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#define NET9 (FILTER_SIZE * FILTER_SIZE * NUM_FILTERS + 9 * POOLED_IMAGE_SIZE * POOLED_IMAGE_SIZE * NUM_FILTERS)
#endif //GA_CNN_DEFINES_CUH
