# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/villa/ga_cnn

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/villa/ga_cnn

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/villa/ga_cnn/CMakeFiles /home/villa/ga_cnn/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/villa/ga_cnn/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ga_cnn

# Build rule for target.
ga_cnn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ga_cnn
.PHONY : ga_cnn

# fast build rule for target.
ga_cnn/fast:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/build
.PHONY : ga_cnn/fast

args_handler/args_extractor.o: args_handler/args_extractor.cu.o

.PHONY : args_handler/args_extractor.o

# target to build an object file
args_handler/args_extractor.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_extractor.cu.o
.PHONY : args_handler/args_extractor.cu.o

args_handler/args_extractor.i: args_handler/args_extractor.cu.i

.PHONY : args_handler/args_extractor.i

# target to preprocess a source file
args_handler/args_extractor.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_extractor.cu.i
.PHONY : args_handler/args_extractor.cu.i

args_handler/args_extractor.s: args_handler/args_extractor.cu.s

.PHONY : args_handler/args_extractor.s

# target to generate assembly for a file
args_handler/args_extractor.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_extractor.cu.s
.PHONY : args_handler/args_extractor.cu.s

args_handler/args_handler.o: args_handler/args_handler.cu.o

.PHONY : args_handler/args_handler.o

# target to build an object file
args_handler/args_handler.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler.cu.o
.PHONY : args_handler/args_handler.cu.o

args_handler/args_handler.i: args_handler/args_handler.cu.i

.PHONY : args_handler/args_handler.i

# target to preprocess a source file
args_handler/args_handler.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler.cu.i
.PHONY : args_handler/args_handler.cu.i

args_handler/args_handler.s: args_handler/args_handler.cu.s

.PHONY : args_handler/args_handler.s

# target to generate assembly for a file
args_handler/args_handler.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler.cu.s
.PHONY : args_handler/args_handler.cu.s

args_handler/args_handler_help.o: args_handler/args_handler_help.cu.o

.PHONY : args_handler/args_handler_help.o

# target to build an object file
args_handler/args_handler_help.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_help.cu.o
.PHONY : args_handler/args_handler_help.cu.o

args_handler/args_handler_help.i: args_handler/args_handler_help.cu.i

.PHONY : args_handler/args_handler_help.i

# target to preprocess a source file
args_handler/args_handler_help.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_help.cu.i
.PHONY : args_handler/args_handler_help.cu.i

args_handler/args_handler_help.s: args_handler/args_handler_help.cu.s

.PHONY : args_handler/args_handler_help.s

# target to generate assembly for a file
args_handler/args_handler_help.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_help.cu.s
.PHONY : args_handler/args_handler_help.cu.s

args_handler/args_handler_version.o: args_handler/args_handler_version.cu.o

.PHONY : args_handler/args_handler_version.o

# target to build an object file
args_handler/args_handler_version.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_version.cu.o
.PHONY : args_handler/args_handler_version.cu.o

args_handler/args_handler_version.i: args_handler/args_handler_version.cu.i

.PHONY : args_handler/args_handler_version.i

# target to preprocess a source file
args_handler/args_handler_version.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_version.cu.i
.PHONY : args_handler/args_handler_version.cu.i

args_handler/args_handler_version.s: args_handler/args_handler_version.cu.s

.PHONY : args_handler/args_handler_version.s

# target to generate assembly for a file
args_handler/args_handler_version.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/args_handler/args_handler_version.cu.s
.PHONY : args_handler/args_handler_version.cu.s

data/data_loader.o: data/data_loader.cu.o

.PHONY : data/data_loader.o

# target to build an object file
data/data_loader.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader.cu.o
.PHONY : data/data_loader.cu.o

data/data_loader.i: data/data_loader.cu.i

.PHONY : data/data_loader.i

# target to preprocess a source file
data/data_loader.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader.cu.i
.PHONY : data/data_loader.cu.i

data/data_loader.s: data/data_loader.cu.s

.PHONY : data/data_loader.s

# target to generate assembly for a file
data/data_loader.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader.cu.s
.PHONY : data/data_loader.cu.s

data/data_loader_cpu.o: data/data_loader_cpu.cu.o

.PHONY : data/data_loader_cpu.o

# target to build an object file
data/data_loader_cpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_cpu.cu.o
.PHONY : data/data_loader_cpu.cu.o

data/data_loader_cpu.i: data/data_loader_cpu.cu.i

.PHONY : data/data_loader_cpu.i

# target to preprocess a source file
data/data_loader_cpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_cpu.cu.i
.PHONY : data/data_loader_cpu.cu.i

data/data_loader_cpu.s: data/data_loader_cpu.cu.s

.PHONY : data/data_loader_cpu.s

# target to generate assembly for a file
data/data_loader_cpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_cpu.cu.s
.PHONY : data/data_loader_cpu.cu.s

data/data_loader_gpu.o: data/data_loader_gpu.cu.o

.PHONY : data/data_loader_gpu.o

# target to build an object file
data/data_loader_gpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_gpu.cu.o
.PHONY : data/data_loader_gpu.cu.o

data/data_loader_gpu.i: data/data_loader_gpu.cu.i

.PHONY : data/data_loader_gpu.i

# target to preprocess a source file
data/data_loader_gpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_gpu.cu.i
.PHONY : data/data_loader_gpu.cu.i

data/data_loader_gpu.s: data/data_loader_gpu.cu.s

.PHONY : data/data_loader_gpu.s

# target to generate assembly for a file
data/data_loader_gpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_loader_gpu.cu.s
.PHONY : data/data_loader_gpu.cu.s

data/data_utils.o: data/data_utils.cu.o

.PHONY : data/data_utils.o

# target to build an object file
data/data_utils.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_utils.cu.o
.PHONY : data/data_utils.cu.o

data/data_utils.i: data/data_utils.cu.i

.PHONY : data/data_utils.i

# target to preprocess a source file
data/data_utils.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_utils.cu.i
.PHONY : data/data_utils.cu.i

data/data_utils.s: data/data_utils.cu.s

.PHONY : data/data_utils.s

# target to generate assembly for a file
data/data_utils.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/data_utils.cu.s
.PHONY : data/data_utils.cu.s

data/file_loader.o: data/file_loader.cu.o

.PHONY : data/file_loader.o

# target to build an object file
data/file_loader.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/file_loader.cu.o
.PHONY : data/file_loader.cu.o

data/file_loader.i: data/file_loader.cu.i

.PHONY : data/file_loader.i

# target to preprocess a source file
data/file_loader.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/file_loader.cu.i
.PHONY : data/file_loader.cu.i

data/file_loader.s: data/file_loader.cu.s

.PHONY : data/file_loader.s

# target to generate assembly for a file
data/file_loader.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/data/file_loader.cu.s
.PHONY : data/file_loader.cu.s

defines.o: defines.cu.o

.PHONY : defines.o

# target to build an object file
defines.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/defines.cu.o
.PHONY : defines.cu.o

defines.i: defines.cu.i

.PHONY : defines.i

# target to preprocess a source file
defines.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/defines.cu.i
.PHONY : defines.cu.i

defines.s: defines.cu.s

.PHONY : defines.s

# target to generate assembly for a file
defines.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/defines.cu.s
.PHONY : defines.cu.s

genetic/evolve_population.o: genetic/evolve_population.cu.o

.PHONY : genetic/evolve_population.o

# target to build an object file
genetic/evolve_population.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population.cu.o
.PHONY : genetic/evolve_population.cu.o

genetic/evolve_population.i: genetic/evolve_population.cu.i

.PHONY : genetic/evolve_population.i

# target to preprocess a source file
genetic/evolve_population.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population.cu.i
.PHONY : genetic/evolve_population.cu.i

genetic/evolve_population.s: genetic/evolve_population.cu.s

.PHONY : genetic/evolve_population.s

# target to generate assembly for a file
genetic/evolve_population.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population.cu.s
.PHONY : genetic/evolve_population.cu.s

genetic/evolve_population_cpu.o: genetic/evolve_population_cpu.cu.o

.PHONY : genetic/evolve_population_cpu.o

# target to build an object file
genetic/evolve_population_cpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_cpu.cu.o
.PHONY : genetic/evolve_population_cpu.cu.o

genetic/evolve_population_cpu.i: genetic/evolve_population_cpu.cu.i

.PHONY : genetic/evolve_population_cpu.i

# target to preprocess a source file
genetic/evolve_population_cpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_cpu.cu.i
.PHONY : genetic/evolve_population_cpu.cu.i

genetic/evolve_population_cpu.s: genetic/evolve_population_cpu.cu.s

.PHONY : genetic/evolve_population_cpu.s

# target to generate assembly for a file
genetic/evolve_population_cpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_cpu.cu.s
.PHONY : genetic/evolve_population_cpu.cu.s

genetic/evolve_population_gpu.o: genetic/evolve_population_gpu.cu.o

.PHONY : genetic/evolve_population_gpu.o

# target to build an object file
genetic/evolve_population_gpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_gpu.cu.o
.PHONY : genetic/evolve_population_gpu.cu.o

genetic/evolve_population_gpu.i: genetic/evolve_population_gpu.cu.i

.PHONY : genetic/evolve_population_gpu.i

# target to preprocess a source file
genetic/evolve_population_gpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_gpu.cu.i
.PHONY : genetic/evolve_population_gpu.cu.i

genetic/evolve_population_gpu.s: genetic/evolve_population_gpu.cu.s

.PHONY : genetic/evolve_population_gpu.s

# target to generate assembly for a file
genetic/evolve_population_gpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/genetic/evolve_population_gpu.cu.s
.PHONY : genetic/evolve_population_gpu.cu.s

info/device_info.o: info/device_info.cu.o

.PHONY : info/device_info.o

# target to build an object file
info/device_info.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/info/device_info.cu.o
.PHONY : info/device_info.cu.o

info/device_info.i: info/device_info.cu.i

.PHONY : info/device_info.i

# target to preprocess a source file
info/device_info.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/info/device_info.cu.i
.PHONY : info/device_info.cu.i

info/device_info.s: info/device_info.cu.s

.PHONY : info/device_info.s

# target to generate assembly for a file
info/device_info.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/info/device_info.cu.s
.PHONY : info/device_info.cu.s

main.o: main.cu.o

.PHONY : main.o

# target to build an object file
main.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/main.cu.o
.PHONY : main.cu.o

main.i: main.cu.i

.PHONY : main.i

# target to preprocess a source file
main.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/main.cu.i
.PHONY : main.cu.i

main.s: main.cu.s

.PHONY : main.s

# target to generate assembly for a file
main.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/main.cu.s
.PHONY : main.cu.s

network/fitness_calculator.o: network/fitness_calculator.cu.o

.PHONY : network/fitness_calculator.o

# target to build an object file
network/fitness_calculator.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator.cu.o
.PHONY : network/fitness_calculator.cu.o

network/fitness_calculator.i: network/fitness_calculator.cu.i

.PHONY : network/fitness_calculator.i

# target to preprocess a source file
network/fitness_calculator.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator.cu.i
.PHONY : network/fitness_calculator.cu.i

network/fitness_calculator.s: network/fitness_calculator.cu.s

.PHONY : network/fitness_calculator.s

# target to generate assembly for a file
network/fitness_calculator.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator.cu.s
.PHONY : network/fitness_calculator.cu.s

network/fitness_calculator_cpu.o: network/fitness_calculator_cpu.cu.o

.PHONY : network/fitness_calculator_cpu.o

# target to build an object file
network/fitness_calculator_cpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_cpu.cu.o
.PHONY : network/fitness_calculator_cpu.cu.o

network/fitness_calculator_cpu.i: network/fitness_calculator_cpu.cu.i

.PHONY : network/fitness_calculator_cpu.i

# target to preprocess a source file
network/fitness_calculator_cpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_cpu.cu.i
.PHONY : network/fitness_calculator_cpu.cu.i

network/fitness_calculator_cpu.s: network/fitness_calculator_cpu.cu.s

.PHONY : network/fitness_calculator_cpu.s

# target to generate assembly for a file
network/fitness_calculator_cpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_cpu.cu.s
.PHONY : network/fitness_calculator_cpu.cu.s

network/fitness_calculator_gpu.o: network/fitness_calculator_gpu.cu.o

.PHONY : network/fitness_calculator_gpu.o

# target to build an object file
network/fitness_calculator_gpu.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_gpu.cu.o
.PHONY : network/fitness_calculator_gpu.cu.o

network/fitness_calculator_gpu.i: network/fitness_calculator_gpu.cu.i

.PHONY : network/fitness_calculator_gpu.i

# target to preprocess a source file
network/fitness_calculator_gpu.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_gpu.cu.i
.PHONY : network/fitness_calculator_gpu.cu.i

network/fitness_calculator_gpu.s: network/fitness_calculator_gpu.cu.s

.PHONY : network/fitness_calculator_gpu.s

# target to generate assembly for a file
network/fitness_calculator_gpu.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/fitness_calculator_gpu.cu.s
.PHONY : network/fitness_calculator_gpu.cu.s

network/init_networks.o: network/init_networks.cu.o

.PHONY : network/init_networks.o

# target to build an object file
network/init_networks.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks.cu.o
.PHONY : network/init_networks.cu.o

network/init_networks.i: network/init_networks.cu.i

.PHONY : network/init_networks.i

# target to preprocess a source file
network/init_networks.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks.cu.i
.PHONY : network/init_networks.cu.i

network/init_networks.s: network/init_networks.cu.s

.PHONY : network/init_networks.s

# target to generate assembly for a file
network/init_networks.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks.cu.s
.PHONY : network/init_networks.cu.s

network/init_networks_utils.o: network/init_networks_utils.cu.o

.PHONY : network/init_networks_utils.o

# target to build an object file
network/init_networks_utils.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks_utils.cu.o
.PHONY : network/init_networks_utils.cu.o

network/init_networks_utils.i: network/init_networks_utils.cu.i

.PHONY : network/init_networks_utils.i

# target to preprocess a source file
network/init_networks_utils.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks_utils.cu.i
.PHONY : network/init_networks_utils.cu.i

network/init_networks_utils.s: network/init_networks_utils.cu.s

.PHONY : network/init_networks_utils.s

# target to generate assembly for a file
network/init_networks_utils.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/network/init_networks_utils.cu.s
.PHONY : network/init_networks_utils.cu.s

output/output_utils.o: output/output_utils.cu.o

.PHONY : output/output_utils.o

# target to build an object file
output/output_utils.cu.o:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/output/output_utils.cu.o
.PHONY : output/output_utils.cu.o

output/output_utils.i: output/output_utils.cu.i

.PHONY : output/output_utils.i

# target to preprocess a source file
output/output_utils.cu.i:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/output/output_utils.cu.i
.PHONY : output/output_utils.cu.i

output/output_utils.s: output/output_utils.cu.s

.PHONY : output/output_utils.s

# target to generate assembly for a file
output/output_utils.cu.s:
	$(MAKE) -f CMakeFiles/ga_cnn.dir/build.make CMakeFiles/ga_cnn.dir/output/output_utils.cu.s
.PHONY : output/output_utils.cu.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ga_cnn"
	@echo "... args_handler/args_extractor.o"
	@echo "... args_handler/args_extractor.i"
	@echo "... args_handler/args_extractor.s"
	@echo "... args_handler/args_handler.o"
	@echo "... args_handler/args_handler.i"
	@echo "... args_handler/args_handler.s"
	@echo "... args_handler/args_handler_help.o"
	@echo "... args_handler/args_handler_help.i"
	@echo "... args_handler/args_handler_help.s"
	@echo "... args_handler/args_handler_version.o"
	@echo "... args_handler/args_handler_version.i"
	@echo "... args_handler/args_handler_version.s"
	@echo "... data/data_loader.o"
	@echo "... data/data_loader.i"
	@echo "... data/data_loader.s"
	@echo "... data/data_loader_cpu.o"
	@echo "... data/data_loader_cpu.i"
	@echo "... data/data_loader_cpu.s"
	@echo "... data/data_loader_gpu.o"
	@echo "... data/data_loader_gpu.i"
	@echo "... data/data_loader_gpu.s"
	@echo "... data/data_utils.o"
	@echo "... data/data_utils.i"
	@echo "... data/data_utils.s"
	@echo "... data/file_loader.o"
	@echo "... data/file_loader.i"
	@echo "... data/file_loader.s"
	@echo "... defines.o"
	@echo "... defines.i"
	@echo "... defines.s"
	@echo "... genetic/evolve_population.o"
	@echo "... genetic/evolve_population.i"
	@echo "... genetic/evolve_population.s"
	@echo "... genetic/evolve_population_cpu.o"
	@echo "... genetic/evolve_population_cpu.i"
	@echo "... genetic/evolve_population_cpu.s"
	@echo "... genetic/evolve_population_gpu.o"
	@echo "... genetic/evolve_population_gpu.i"
	@echo "... genetic/evolve_population_gpu.s"
	@echo "... info/device_info.o"
	@echo "... info/device_info.i"
	@echo "... info/device_info.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... network/fitness_calculator.o"
	@echo "... network/fitness_calculator.i"
	@echo "... network/fitness_calculator.s"
	@echo "... network/fitness_calculator_cpu.o"
	@echo "... network/fitness_calculator_cpu.i"
	@echo "... network/fitness_calculator_cpu.s"
	@echo "... network/fitness_calculator_gpu.o"
	@echo "... network/fitness_calculator_gpu.i"
	@echo "... network/fitness_calculator_gpu.s"
	@echo "... network/init_networks.o"
	@echo "... network/init_networks.i"
	@echo "... network/init_networks.s"
	@echo "... network/init_networks_utils.o"
	@echo "... network/init_networks_utils.i"
	@echo "... network/init_networks_utils.s"
	@echo "... output/output_utils.o"
	@echo "... output/output_utils.i"
	@echo "... output/output_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

